version: '3.5'

services:
  mysql-jdev:
    image: mysql
    ports:
      - 6033:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: admin
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      customnetwork:
        ipv4_address: 172.20.0.10


  phpmyadmin-jdev:
      image: phpmyadmin
      restart: always
      ports:
        - 8082:80
      environment:
        - PMA_ARBITRARY=1
      networks:
        customnetwork:
          ipv4_address: 172.20.0.11


  php-7.4-jdev:
#    image: wyveo/nginx-php-fpm:php74
    build:
      context: .
      dockerfile: environment/php7.4/Dockerfile
    ports:
      - 8888:80
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./html:/usr/share/nginx/html

    depends_on:
      - mysql-jdev
      - phpmyadmin-jdev

    networks:
      customnetwork:
        ipv4_address: 172.20.0.12


networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
