version: '3'

services:
  web:
    build:
      context: ./environment/php8.1
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    networks:
      customnetwork:
        ipv4_address: 182.20.0.12

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123123
      MYSQL_DATABASE: devcett
      MYSQL_USER: admin         
      MYSQL_PASSWORD: admin123123
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      customnetwork:
        ipv4_address: 182.20.0.11
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:8080"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin123123
      PMA_USER: admin
      PMA_PASSWORD: admin123123
    networks:
      customnetwork:
        ipv4_address: 182.20.0.13

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 182.20.0.0/16
